#!/usr/bin/env python3
"""
scripts/32_build_colab_gpu_package.py

Builds bruise_colab_gpu_full.zip: everything needed to run
scripts/31_benchmark_640_local.py --device cuda:0 on the FULL 185-image
fixed_consensus_test set on Colab (Google Drive, uploaded once).

Supersedes bruise_colab_gpu_test.zip (1-image smoke test) for real
GPU-comparable numbers. That zip is left untouched -- this writes a new file.

WHY SELECTIVE COPY, NOT WHOLE RUN DIRS
---------------------------------------
yolo_sem_direct/ and yolo_sem_distilled/ are ~2.2GB each on disk (full
Ultralytics training artifacts -- every epoch's weights, plots, etc). Only
ultralytics_runs/train/weights/best.pt and threshold_search.csv are ever
read by load_yolo_model() (pipeline/yolo_threshold_temp.py) or the
benchmark. Same idea for SegFormer runs: best_model*.pt + threshold_search.csv
is everything read from those directories.

WHY threshold_search.csv IS NOT OPTIONAL
------------------------------------------
pipeline/models.py::load_segformer_model() and
pipeline/yolo_threshold_temp.py::load_yolo_model() both resolve the
calibrated (threshold, temperature) pair from run_dir/threshold_search.csv
(top row by mean_dice) -- there is no fallback default. Omitting it (as the
earlier 1-image smoke-test zip did) makes every model fail to load.

WHY THE MANIFEST GETS REWRITTEN
---------------------------------
fixed_consensus_test/manifest.csv's image_path/mask_path columns are
absolute Windows paths (C:/BRUISE_SEGMENTATION_PROJECT/...) baked in by
earlier local-path-fixup work (see scripts/fix_local_manifest_paths.py).
pipeline/data.py hands these straight to cv2.imread() with no re-rooting, so
they're rewritten here to relative paths -- same prefix-strip idea as that
script. Relative paths resolve correctly on Colab regardless of where the
zip gets unzipped, as long as the benchmark is run with that unzipped folder
as the working directory (the notebook does `%cd` before running it).
"""
from __future__ import annotations

import argparse
import io
import sys
import zipfile
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from pipeline.data import normalize_manifest
from pipeline.io_utils import setup_logging

logger = setup_logging()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OLD_PREFIX = "C:/BRUISE_SEGMENTATION_PROJECT/"

CODE_FILES = [
    "scripts/31_benchmark_640_local.py",
    "configs/common_train.yaml",
    "configs/benchmark_640_models.yaml",
]
CODE_DIRS = ["pipeline"]

SEGFORMER_RUNS = ["segformer_b2_teacher", "segformer_b0_direct", "segformer_b0_distilled"]
SEGFORMER_FILES = ["best_model.pt", "best_model.pre_migration_backup.pt", "threshold_search.csv"]

YOLO_RUNS = ["yolo_sem_direct", "yolo_sem_distilled"]
YOLO_FILES = ["ultralytics_runs/train/weights/best.pt", "threshold_search.csv"]

PRETRAINED_DIR = "pretrained_weights"

DATASET_ROOT_ARC = "labelbox_paul_orc_dataset_full_consensus/fixed_consensus_test"
DATASET_SUBDIRS = ["images", "masks_majority_vote"]
MANIFEST_REL = f"{DATASET_ROOT_ARC}/manifest.csv"

# --- Validation split (added so a threshold sweep can run on Colab) ---------
# The 134 val rows of the subject-level split. Their images/masks live in
# train_paul_wl_minus_test_subjects/, a directory that ALSO holds the 697
# train images -- so these are packaged file-by-file from the manifest, never
# with add_dir(), which would drag in all 831 and add ~1.9GB of images that
# nothing in the package reads.
VAL_SPLIT_SRC = "splits/train_val_split.csv"
VAL_MANIFEST_REL = "splits/val_split.csv"

NEW_PATHS_YAML = f"""# Colab GPU package -- all paths are RELATIVE, resolved against whatever
# directory you `%cd` into before running the script (the root of this
# unzipped folder). Generated by scripts/32_build_colab_gpu_package.py --
# see that script's docstring for why paths.yaml and manifest.csv are
# rewritten rather than copied as-is.
dataset_root: .
project_root: .

# The 185-image held-out test set. Scored on; never fitted on.
fixed_test_manifest: {MANIFEST_REL}

# The 134 val images, for fitting operating points (threshold sweeps).
# This is a DIFFERENT file from fixed_test_manifest -- that separation is the
# whole point of shipping it, so a sweep can be fitted somewhere other than
# the set it is later scored on.
val_manifest: {VAL_MANIFEST_REL}

# NOTE: this package contains NO train images -- only val + test. train_manifest
# is aliased to the val manifest purely so io_utils.validate_paths() (which
# requires the key to exist on disk) passes. Do not train from this package.
# Earlier versions of this file aliased train_manifest to the TEST manifest,
# which silently turned any sweep reading it into a test-set leak.
train_manifest: {VAL_MANIFEST_REL}

pretrained_weights_root: pretrained_weights
segformer_b2_pretrained: pretrained_weights/segformer_mit_b2
segformer_b0_pretrained: pretrained_weights/segformer_mit_b0
yolo_sem_weights: pretrained_weights/yolo26n-sem.pt
"""


def add_dir(zf: zipfile.ZipFile, real_dir: Path, arc_prefix: str) -> None:
    for path in sorted(real_dir.rglob("*")):
        if path.is_file() and "__pycache__" not in path.parts:
            arcname = f"{arc_prefix}/{path.relative_to(real_dir).as_posix()}"
            zf.write(path, arcname)


def rewritten_manifest_text() -> str:
    src = PROJECT_ROOT / MANIFEST_REL
    text = src.read_text(encoding="utf-8")
    if OLD_PREFIX not in text:
        raise RuntimeError(
            f"Expected prefix {OLD_PREFIX!r} not found in {src} -- has it already "
            "been rewritten, or did the local path convention change?"
        )
    return text.replace(OLD_PREFIX, "")


def val_manifest_text() -> str:
    """The split CSV's val rows only, with absolute paths made relative.

    Same prefix-strip idea as rewritten_manifest_text(), but row-filtered: the
    train rows are dropped because this package deliberately ships no train
    images, and a manifest pointing at files that aren't in the zip would fail
    verify_package() (correctly -- a manifest should never reference a file the
    package doesn't contain).
    """
    src = PROJECT_ROOT / VAL_SPLIT_SRC
    frame = pd.read_csv(src)

    if "split" not in frame.columns:
        raise RuntimeError(f"{src} has no 'split' column -- run 00_build_split.py first.")
    val = frame[frame["split"] == "val"].copy()
    if val.empty:
        raise RuntimeError(f"{src} contains no rows with split == 'val'.")

    for col in ("image_path", "mask_path"):
        if col not in val.columns:
            raise RuntimeError(f"{src} is missing the {col!r} column.")
        values = val[col].astype(str)
        bad = values[~values.str.startswith(OLD_PREFIX)]
        if not bad.empty:
            raise RuntimeError(
                f"{src}: {len(bad)} {col} value(s) do not start with {OLD_PREFIX!r} "
                f"(e.g. {bad.iloc[0]!r}) -- cannot rewrite them to relative paths."
            )
        val[col] = values.str.replace(OLD_PREFIX, "", regex=False)

    buffer = io.StringIO()
    val.to_csv(buffer, index=False)
    return buffer.getvalue()


def verify_package(zip_path: Path) -> None:
    """Sanity-check the zip before calling it ready: threshold_search.csv
    present for all 5 models, and every image_path/mask_path the rewritten
    manifest points at actually got written into the zip. Catches a broken
    package locally instead of failing partway through a Colab run."""
    with zipfile.ZipFile(zip_path) as zf:
        names = set(zf.namelist())

        for run in SEGFORMER_RUNS + YOLO_RUNS:
            key = f"{run}/threshold_search.csv"
            if key not in names:
                raise RuntimeError(f"Missing {key} in built package")

        if VAL_MANIFEST_REL not in names:
            raise RuntimeError(f"Missing {VAL_MANIFEST_REL} in built package")

        manifest_bytes = zf.read(MANIFEST_REL)
        val_bytes = zf.read(VAL_MANIFEST_REL)

    df = normalize_manifest(pd.read_csv(io.BytesIO(manifest_bytes)))
    val_df = normalize_manifest(pd.read_csv(io.BytesIO(val_bytes)))

    missing = []
    for label, frame in (("test", df), ("val", val_df)):
        for col in ("image_path", "mask_path"):
            for value in frame[col]:
                if value.replace("\\", "/") not in names:
                    missing.append(f"[{label}.{col}] {value}")
    if missing:
        raise RuntimeError(
            f"{len(missing)} manifest path(s) not present in the zip:\n" + "\n".join(missing[:20])
        )

    # The reason the val split is shipped at all is so an operating point can be
    # fitted somewhere other than the set it is scored on. If the two manifests
    # ever overlap, that guarantee is gone and every threshold fitted on "val"
    # is partly fitted on test -- which would silently inflate the reported test
    # numbers rather than crash. Cheap to assert, catastrophic to miss.
    overlap = set(df["image_path"]) & set(val_df["image_path"])
    if overlap:
        raise RuntimeError(
            f"{len(overlap)} image(s) appear in BOTH the val and test manifests "
            f"(e.g. {sorted(overlap)[0]}). Fitting a threshold on val would leak test data."
        )
    subject_overlap = set(df["subject"]) & set(val_df["subject"])
    if subject_overlap:
        raise RuntimeError(
            f"{len(subject_overlap)} subject(s) appear in BOTH val and test "
            f"(e.g. {sorted(subject_overlap)[0]}). The split is supposed to be subject-level."
        )

    logger.info(
        "Verified: %d test + %d val manifest rows all resolve inside the zip; "
        "no image or subject overlap between them; threshold_search.csv present "
        "for all 5 models.", len(df), len(val_df)
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(PROJECT_ROOT / "bruise_colab_gpu_full.zip"))
    args = ap.parse_args()
    out_path = Path(args.out)

    manifest_text = rewritten_manifest_text()
    val_text = val_manifest_text()
    val_df = pd.read_csv(io.StringIO(val_text))

    logger.info("Building %s ...", out_path)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for rel in CODE_FILES:
            zf.write(PROJECT_ROOT / rel, rel)
        for rel in CODE_DIRS:
            add_dir(zf, PROJECT_ROOT / rel, rel)

        zf.writestr("configs/paths.yaml", NEW_PATHS_YAML)

        for run in SEGFORMER_RUNS:
            for fname in SEGFORMER_FILES:
                zf.write(PROJECT_ROOT / run / fname, f"{run}/{fname}")

        for run in YOLO_RUNS:
            for fname in YOLO_FILES:
                zf.write(PROJECT_ROOT / run / fname, f"{run}/{fname}")

        add_dir(zf, PROJECT_ROOT / PRETRAINED_DIR, PRETRAINED_DIR)

        for sub in DATASET_SUBDIRS:
            add_dir(zf, PROJECT_ROOT / DATASET_ROOT_ARC / sub, f"{DATASET_ROOT_ARC}/{sub}")

        zf.writestr(MANIFEST_REL, manifest_text)

        # Val images/masks, one file per manifest row. Deliberately NOT add_dir()
        # -- see VAL_SPLIT_SRC's comment: the source directory also holds the 697
        # train images this package has no use for.
        for col in ("image_path", "mask_path"):
            for rel in val_df[col].astype(str):
                zf.write(PROJECT_ROOT / rel, rel)

        zf.writestr(VAL_MANIFEST_REL, val_text)

    verify_package(out_path)

    size_mb = out_path.stat().st_size / (1024 * 1024)
    logger.info("PASS -- wrote %s (%.0f MB)", out_path, size_mb)


if __name__ == "__main__":
    main()
